# Generated by Django 2.2.3 on 2020-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0003_usuarios_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='zip',
            field=models.CharField(default='93822', max_length=7, null=True),
        ),
    ]
