# Generated by Django 2.2.3 on 2020-10-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0006_auto_20201025_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Sin especificar', max_length=50)),
                ('description', models.CharField(blank=True, default='Sin especificar', max_length=150)),
                ('price', models.FloatField(blank=True, default=0, max_length=20)),
                ('image', models.URLField(blank=True, default='https://imgurl.me/images/2020/10/28/noimagea9f94df30d6506c0.jpg', max_length=600)),
            ],
        ),
    ]
