# Generated by Django 2.2.3 on 2020-10-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0009_auto_20201027_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.CharField(blank=True, default='https://imgurl.me/images/2020/10/28/noimagea9f94df30d6506c0.jpg', max_length=600),
        ),
    ]
