# Generated by Django 2.2.3 on 2020-10-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0011_auto_20201028_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
